"""Add column 'private' to NoteModel

Revision ID: 16719a7c3385
Revises: b89bed4ecfc9
Create Date: 2021-03-12 11:54:39.085850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16719a7c3385'
down_revision = 'b89bed4ecfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
