"""create UserModel

Revision ID: 1cf98a1e74f3
Revises: c488feba2cee
Create Date: 2021-03-09 14:40:33.503327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf98a1e74f3'
down_revision = 'c488feba2cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.create_foreign_key("UserModel", 'user_model', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
