"""create UserModel

Revision ID: 8d64b6aab1f5
Revises: 1cf98a1e74f3
Create Date: 2021-03-09 19:10:37.465545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d64b6aab1f5'
down_revision = '1cf98a1e74f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
