"""add colunm archive

Revision ID: eb561f735473
Revises: 57ecaecd9c34
Create Date: 2021-03-17 12:37:14.716855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb561f735473'
down_revision = '57ecaecd9c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.drop_column('archive')

    # ### end Alembic commands ###
